### ISSUE TITLE
Three bug in occlusion

### ISSUE THREAD

**Issue by BEST8OY** [hgiesel/closet#96] opened 2022-07-14 01:08 UTC
Hello
I found Three bug in browser.
1- Close Menu doesn't function
2- In browser If you select card and active occlusion mode you can see the occlusions but you can't do anything (add or delete occlusion boxes , ...). So **if you want occlusion mode work in browser** you should first select card then select field which contain occlusions then active occlusion mode. 
3- When occlusion mode is active for a card in browser if you suddenly choose another card, the first card copies itself to second card.

I Hope i was able to elaborate issues properly.
- AnkiDesktop
- Windows
- 2.1.54

**Comment by kleinerpirat** [comment] 2022-07-15 18:13
Thanks for reporting these issues!

1. Can't reproduce this. Clicking "Close Menu" closes the context menu for me :thinking: 
2. Peculiar. I'll have to investigate a bit.
3. The rich text input is decoupled from the HTML editor to allow editing of occlusions. Right now, these inputs are only recoupled when the occlusion editor is closed. If you don't close it before switching notes, the field element isn't updated. This should be easy to fix with a hook.

**Comment by BEST8OY** [comment] 2022-07-15 18:49
> Thanks for reporting these issues!
> 
> 1. Can't reproduce this. Clicking "Close Menu" closes the context menu for me 🤔

Huh.
First one was my misunderstanding.
I thought "Close Menu" function was supposed to be exiting occlusion mode without saving changes.
But now i think its function is closing the the menu containing "Close Menu" itself all along.😅

**Comment by BEST8OY** [comment] 2022-07-23 19:25
Well I tested your 2.1.52+fix brnach of closet and the issues i reported were fixed.
I wanted to close the issue but it's better that you close it after the PR got approval.

**Closed** 2022-08-09 05:44 UTC
Labels: bug
